spring.application.name=Blurtle
frontend.urls=http://localhost:5173,http://localhost:5174,https://playblurtle.com,https://www.playblurtle.com

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Explicitly force Flyway to use the correct db connection
spring.flyway.url=jdbc:postgresql://localhost:5432/blurtle
spring.flyway.user=postgres
spring.flyway.password=Drowssap_94

spring.datasource.url=jdbc:postgresql://localhost:5432/blurtle
spring.datasource.username=postgres
spring.datasource.password=Drowssap_94