spring.application.name=Blurtle
frontend.urls=http://localhost:5173,http://localhost:5174,https://playblurtle.com,https://www.playblurtle.com

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.datasource.url=${BLURTLE_DB_URL}
spring.datasource.username=${BLURTLE_DB_USERNAME}
spring.datasource.password=${BLURTLE_DB_PASSWORD}

# Explicitly force Flyway to use the correct db connection
spring.flyway.url=${BLURTLE_DB_URL}
spring.flyway.user=${BLURTLE_DB_USERNAME}
spring.flyway.password=${BLURTLE_DB_PASSWORD}